language: go
before_script:
  - go vet ./...
before_deploy:
  - env GOOS=linux GOARCH=amd64 go build -o timezilla_linux_amd64
deploy:
  provider: releases
  api_key:
    secure: YAskt+54jKSyFzrNq0Arb0rGLDP6InMDHrBXT7DAzFW5eKyKKRYg4r+wFYHWpHe8SDWTN4DeuQG4NDXEYrFpDa4qQsKlIPOx9dY47XHjIpL7z6svCRaUk1adP7HixNd0n4xDtvPGr96jV9/JJgCyxY9KTC1CYikTjKzRFio0yM43kUsVv8U8SBPCfOCumePHrDw/gdP/0X9HLXVJqiJjjNBk3Qhj0lBRR/xQsjO/3Kb+WLvlTG1SMX4EUflX0BVNoSTkI04/Sk5o+JQBmLcPsHqkCuj1JwltedEUqBcnvNvEp6Ut09TvQzQpNMYiSMTqDEX7pB86PS6dmQNyaIpqWWZk6eRVjKJLoECReq8+qKP0Ceqt3w11P64v1VcAxsB3Fw0fDfHVWLffHCIfq6wjhE86qOOOKaTCWUf50BXUYvE3voMWb3Arfd4dSL8JXHLkQRJ0+Ye4SR94xI0XYj549Us4lSiQsR5zii5NGQhiCpUMgHRChpsAQIflikonmiaVheocJS0YooqhNqhUS728BIARqnMknvqCTsCsSIPvhFX11yXoYc7b0BRLwj3xPqacRFSvglyr+46GeI3uNlTermorwk2nwmQNECy17LiNvTMUvVjwAPtzMeZGiWSqbfjxvbsLmKIP9WaD7+bQ+vyE06V/mIehobRDwZQXtROgWt8=
  file: 'timezilla_linux_amd64'
  skip_cleanup: true
  on:
    repo: ctcpip/timezilla
    tags: true
